### ISSUE TITLE
SNP Derived Key always rooted in VMRK

### ISSUE THREAD

**Issue by larrydewey** [vmware-research/certifier-framework-for-confidential-computing#32]
I noticed that it looks like there is a hard-coded values in the key derivation process.  Should the "final key" always be rooted in the VMRK, or is this something a user may specify to be rooted in the VCEK? Would it make sense to have this as an optional value provided in the policy?

https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/e78b65d6153be9251e07ef9f7a1cf5c2b91d9900/src/sev-snp/sev_support.cc#L556

It seems to be a similar situation with the field selection here?

https://github.com/vmware-research/certifier-framework-for-confidential-computing/blob/e78b65d6153be9251e07ef9f7a1cf5c2b91d9900/src/sev-snp/sev_support.cc#L563

**Comment by yelvmw** [comment]
Good point, Larry! The higher level sealing API today does not offer the option to specify sealing parameters yet. But that definitely makes sense. Most likely we will try to come up with a Certifier parameter abstraction to accommodate all the backend differences in the future.

The current assumption is to have the sealed data tied to identities. I think it actually should be rooted to VCEK by default instead and include FIELD_POLICY_MASK in addition to measurement so that no one can enable debug for the VM and unseal some previous secret on the same platform. Thoughts?

**Comment by yelvmw** [comment]
Fix upstreamed.
